### ISSUE TITLE
`v1.0.0` initial roadmap

### ISSUE THREAD

**Issue by AntoniosBarotsis** [AntoniosBarotsis/qr-rs#3]
This issue will keep track of feature requests planned for the `v1.0` release. Most so far are rather small additions so I'll be aggregating them here instead of flooding the repo with issues

## New API arguments

- [x] Image size - c0d60c0a3e1b7e37fd427dc8ad24d38b5b1f89c9
- [x] Background color - 05582890dd1117d6b7e82b5e7fd088a1e0367818
- [x] Select a logo from a list of predetermined images - 44e74f4df556a415b586fcb6bc3bcfd5772ad02e

## Publish

- [x] Automatically build and publish docker image(s) on release
- [x] Automatically build and publish `lib` on crates.io

## Testing

- [x] Write some server tests
- [x] Write some lib tests
- [x] Automate code coverage reporting

## Other

- [x] Keep track of the MSRV

**Comment by AntoniosBarotsis** [comment]
Moving to the [project](https://github.com/users/AntoniosBarotsis/projects/3/views/1).
